all:
	g++ -O3 -std=c++11 0_buildROB.cpp -o buildROB
	g++ -O3 -std=c++11 0_buildCxt.cpp -o buildCxt

dbg:
	g++ -O0 -g -std=c++11 0_buildROB.cpp -o buildROB
	g++ -O0 -g -std=c++11 0_buildCxt.cpp -o buildCxt
