all:
	g++ -O3 -std=c++11 0_buildROB.cpp -o buildROB
	g++ -O3 -std=c++11 0_buildQ.cpp -o buildQ
	g++ -O3 -std=c++11 0_buildML.cpp -o buildML
	g++ -O3 -std=c++11 0_buildCxt.cpp -o buildCxt
	g++ -O3 -std=c++11 8_buildSim.cpp -o buildSim
	g++ -O3 -std=c++11 8_buildQSim.cpp -o buildQSim

dbg:
	g++ -O0 -g -std=c++11 0_buildROB.cpp -o buildROB
	g++ -O0 -g -std=c++11 0_buildQ.cpp -o buildQ
	g++ -O0 -g -std=c++11 0_buildML.cpp -o buildML
	g++ -O0 -g -std=c++11 0_buildCxt.cpp -o buildCxt
	g++ -O0 -g -std=c++11 8_buildSim.cpp -o buildSim
	g++ -O0 -g -std=c++11 8_buildQSim.cpp -o buildQSim
