all:
	g++ -O3 -std=c++11 0_buildROB.cpp -o buildROB
	g++ -O3 -std=c++11 0_buildCxt.cpp -o buildCxt
	g++ -O3 -std=c++11 8_buildSim.cpp -o buildSim

dbg:
	g++ -O0 -g -std=c++11 0_buildROB.cpp -o buildROB
	g++ -O0 -g -std=c++11 0_buildCxt.cpp -o buildCxt
	g++ -O0 -g -std=c++11 8_buildSim.cpp -o buildSim
